name = "Nexamon"
author = "firefloc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1725898390daeec32771005459669fa7def43267efedd87617d5f826c8cb906d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
