name = "Nexamon"
author = "firefloc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1463d6153c8f9eeb6fe243952adc4cb2387df3d2a977e0bbbd791802ef037c84"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
