name = "Nexamon"
author = "firefloc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8062ab365cbbe3df09f556587ff6615f2eb81aaab4a41bfcf4fc67ab620dcc2d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
